// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/internal/types.proto

/*
Package internal is a generated protocol buffer package.

Package internal holds protobuf types used by the server

It is generated from these files:
	server/internal/types.proto

It has these top-level messages:
	RefreshToken
	IDTokenSubject
	AccessToken
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RefreshToken is a message that holds refresh token data used by dex.
type RefreshToken struct {
	RefreshId       string `protobuf:"bytes,1,opt,name=refresh_id,json=refreshId" json:"refresh_id,omitempty"`
	Token           string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	IssuedTimestamp int64  `protobuf:"varint,3,opt,name=issued_timestamp,json=issuedTimestamp" json:"issued_timestamp,omitempty"`
}

func (m *RefreshToken) Reset()                    { *m = RefreshToken{} }
func (m *RefreshToken) String() string            { return proto.CompactTextString(m) }
func (*RefreshToken) ProtoMessage()               {}
func (*RefreshToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RefreshToken) GetRefreshId() string {
	if m != nil {
		return m.RefreshId
	}
	return ""
}

func (m *RefreshToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshToken) GetIssuedTimestamp() int64 {
	if m != nil {
		return m.IssuedTimestamp
	}
	return 0
}

// IDTokenSubject represents both the userID and connID which is returned
// as the "sub" claim in the ID Token.
type IDTokenSubject struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ConnId string `protobuf:"bytes,2,opt,name=conn_id,json=connId" json:"conn_id,omitempty"`
}

func (m *IDTokenSubject) Reset()                    { *m = IDTokenSubject{} }
func (m *IDTokenSubject) String() string            { return proto.CompactTextString(m) }
func (*IDTokenSubject) ProtoMessage()               {}
func (*IDTokenSubject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IDTokenSubject) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *IDTokenSubject) GetConnId() string {
	if m != nil {
		return m.ConnId
	}
	return ""
}

// AccessToken used in the /userinfo endpoint implementation
type AccessToken struct {
	Subject       string   `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	Username      string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email         string   `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	EmailVerified bool     `protobuf:"varint,4,opt,name=email_verified,json=emailVerified" json:"email_verified,omitempty"`
	Groups        []string `protobuf:"bytes,5,rep,name=groups" json:"groups,omitempty"`
	ConnectorData string   `protobuf:"bytes,6,opt,name=connector_data,json=connectorData" json:"connector_data,omitempty"`
	ConnectorId   string   `protobuf:"bytes,7,opt,name=connector_id,json=connectorId" json:"connector_id,omitempty"`
	// Time at which the access token expires, represented as a unix time.
	//
	// This is the same value as the id_token.
	Expiry int64 `protobuf:"varint,8,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *AccessToken) Reset()                    { *m = AccessToken{} }
func (m *AccessToken) String() string            { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()               {}
func (*AccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AccessToken) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AccessToken) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AccessToken) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AccessToken) GetEmailVerified() bool {
	if m != nil {
		return m.EmailVerified
	}
	return false
}

func (m *AccessToken) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *AccessToken) GetConnectorData() string {
	if m != nil {
		return m.ConnectorData
	}
	return ""
}

func (m *AccessToken) GetConnectorId() string {
	if m != nil {
		return m.ConnectorId
	}
	return ""
}

func (m *AccessToken) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

func init() {
	proto.RegisterType((*RefreshToken)(nil), "internal.RefreshToken")
	proto.RegisterType((*IDTokenSubject)(nil), "internal.IDTokenSubject")
	proto.RegisterType((*AccessToken)(nil), "internal.AccessToken")
}

func init() { proto.RegisterFile("server/internal/types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x91, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0x87, 0x15, 0x4a, 0xd3, 0xf4, 0xfa, 0x07, 0x64, 0x21, 0xb0, 0x40, 0x48, 0xa1, 0x12, 0x52,
	0x59, 0xe8, 0xc0, 0x13, 0x80, 0xba, 0x64, 0x0d, 0x15, 0x6b, 0xe4, 0xc6, 0x57, 0x30, 0x34, 0x76,
	0x64, 0x3b, 0x15, 0x7d, 0x75, 0x26, 0x64, 0x3b, 0x49, 0xb7, 0x7c, 0xdf, 0x5d, 0x7e, 0x77, 0xb6,
	0xe1, 0xce, 0xa0, 0x3e, 0xa0, 0x5e, 0x09, 0x69, 0x51, 0x4b, 0xb6, 0x5f, 0xd9, 0x63, 0x8d, 0xe6,
	0xb9, 0xd6, 0xca, 0x2a, 0x92, 0x74, 0x76, 0x21, 0x61, 0x9a, 0xe3, 0x4e, 0xa3, 0xf9, 0xda, 0xa8,
	0x1f, 0x94, 0xe4, 0x1e, 0x40, 0x07, 0x2e, 0x04, 0xa7, 0x51, 0x1a, 0x2d, 0xc7, 0xf9, 0xb8, 0x35,
	0x19, 0x27, 0x57, 0x30, 0xb4, 0xae, 0x8f, 0x9e, 0xf9, 0x4a, 0x00, 0xf2, 0x04, 0x97, 0xc2, 0x98,
	0x06, 0x79, 0x61, 0x45, 0x85, 0xc6, 0xb2, 0xaa, 0xa6, 0x83, 0x34, 0x5a, 0x0e, 0xf2, 0x8b, 0xe0,
	0x37, 0x9d, 0x5e, 0xbc, 0xc1, 0x3c, 0x5b, 0xfb, 0x51, 0xef, 0xcd, 0xf6, 0x1b, 0x4b, 0x4b, 0x6e,
	0x60, 0xd4, 0x18, 0xd4, 0xa7, 0x71, 0xb1, 0xc3, 0x8c, 0xbb, 0x42, 0xa9, 0xa4, 0x74, 0x85, 0x30,
	0x2d, 0x76, 0x98, 0xf1, 0xc5, 0x5f, 0x04, 0x93, 0xd7, 0xb2, 0x44, 0x63, 0xc2, 0xce, 0x14, 0x46,
	0x26, 0x84, 0xb5, 0x09, 0x1d, 0x92, 0x5b, 0x48, 0x5c, 0x98, 0x64, 0x15, 0xb6, 0x19, 0x3d, 0xbb,
	0xa3, 0x60, 0xc5, 0xc4, 0xde, 0x6f, 0x3a, 0xce, 0x03, 0x90, 0x47, 0x98, 0xfb, 0x8f, 0xe2, 0x80,
	0x5a, 0xec, 0x04, 0x72, 0x7a, 0x9e, 0x46, 0xcb, 0x24, 0x9f, 0x79, 0xfb, 0xd1, 0x4a, 0x72, 0x0d,
	0xf1, 0xa7, 0x56, 0x4d, 0x6d, 0xe8, 0x30, 0x1d, 0xb8, 0xd5, 0x02, 0xb9, 0xdf, 0xdd, 0x92, 0x58,
	0x5a, 0xa5, 0x0b, 0xce, 0x2c, 0xa3, 0xb1, 0x4f, 0x9f, 0xf5, 0x76, 0xcd, 0x2c, 0x23, 0x0f, 0x30,
	0x3d, 0xb5, 0x09, 0x4e, 0x47, 0xbe, 0x69, 0xd2, 0xbb, 0xcc, 0x4f, 0xc0, 0xdf, 0x5a, 0xe8, 0x23,
	0x4d, 0xfc, 0x4d, 0xb6, 0xb4, 0x8d, 0xfd, 0x0b, 0xbe, 0xfc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x03,
	0x03, 0x47, 0xbc, 0xe0, 0x01, 0x00, 0x00,
}
